
export const PRODUCTS = [
  {
    id: "1",
    productName: "IPhone 13 Pro",
    category: "Tecnologia",
    price: 999.99,
    stock: 10,
    productImage: "https://ibb.co/2qRbv5q",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "2",
    productName: "Macbook Pro 2022 (M1)",
    category: "Tecnologia",
    price: 1999.99,
    stock: 10,
    productImage: "https://ibb.co/N9dY2mc",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "3",
    productName: "Cannon M50 Camera",
    category: "Tecnologia",
    price: 699.99,
    stock: 10,
    productImage: "https://ibb.co/jyNw9wJ",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "4",
    productName: "WLS Van Gogh Denim Jacket",
    category: "Vestimenta",
    price: 228.99,
    stock: 10,
    productImage: "https://ibb.co/bKLpx3s",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "5",
    productName: "LED Light Strips",
    category: "Tecnologia",
    price: 19.99,
    stock: 10,
    productImage: "https://ibb.co/Nr2WWNL",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "6",
    productName: "SPECTRUM LS TEE",
    category: "Vestimenta",
    price: 68.99,
    stock: 10,
    productImage: "https://ibb.co/Cn6wGHZ",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "7",
    productName: "AUTO SERVICE SHIRT by GOLF WANG",
    category: "Vestimenta",
    price: 120.99,
    stock: 10,
    productImage: "https://ibb.co/2csNkdq",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "8",
    productName: "DON'T TRIP UNSTRUCTURED HAT",
    category: "Vestimenta",
    price: 40.99,
    stock: 10,
    productImage: "https://ibb.co/bPCCMcn",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
];

export default PRODUCTS
