
export const PRODUCTS = [
  {
    id: "1",
    productName: "IPhone 13 Pro",
    category: "Tecnologia",
    price: 999.99,
    stock: 10,
    productImage: "./src/assets/products/1.png",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "2",
    productName: "Macbook Pro 2022 (M1)",
    category: "Tecnologia",
    price: 1999.99,
    stock: 10,
    productImage: "./src/assets/products/2.png",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "3",
    productName: "Cannon M50 Camera",
    category: "Tecnologia",
    price: 699.99,
    stock: 10,
    productImage: "./src/assets/products/3.png",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "4",
    productName: "WLS Van Gogh Denim Jacket",
    category: "Vestimenta",
    price: 228.99,
    stock: 10,
    productImage: "./src/assets/products/4.png",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "5",
    productName: "LED Light Strips",
    category: "Tecnologia",
    price: 19.99,
    stock: 10,
    productImage: "./src/assets/products/5.png",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "6",
    productName: "SPECTRUM LS TEE",
    category: "Vestimenta",
    price: 68.99,
    stock: 10,
    productImage: "./src/assets/products/6.png",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "7",
    productName: "AUTO SERVICE SHIRT by GOLF WANG",
    category: "Vestimenta",
    price: 120.99,
    stock: 10,
    productImage: "./src/assets/products/7.png",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "8",
    productName: "DON'T TRIP UNSTRUCTURED HAT",
    category: "Vestimenta",
    price: 40.99,
    stock: 10,
    productImage: "./src/assets/products/8.png",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
];
